apiVersion: v1
kind: Service
metadata:
  labels:
    run: echo-server
  name: echo-server
spec:
  ports:
  - name: http-8080
    port: 8080
    protocol: TCP
    targetPort: 5678
  selector:
    app: echo-server
  type: ClusterIP